apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hull
  labels:
    name: hull
spec:
  template:
    metadata:
      labels:
        name: hull
    spec:
      containers:
        - name: hull
          # set project name here:
          image: eu.gcr.io/hulldev-michaloo/hull:v2
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_USER
              value:
            - name: MYSQL_PASSWORD
              value:
---
apiVersion: v1
kind: Service
metadata:
  name: hull-lb
  labels:
    name: hull-lb
spec:
  type: LoadBalancer
  # set your external IP here:
  loadBalancerIP: 104.199.2.150
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: hull
