apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [acme]
    email = "admin@hull.io"
    storageFile = "/acme/acme.json"
    entryPoint = "https"
    [[acme.domains]]
    main = "michaloo.hull.rocks"
    sans = ["accounts.michaloo.hull.rocks", "dashboard.michaloo.hull.rocks", "super.michaloo.hull.rocks"]
